dist: xenial
language: python
sudo: false
os:
- linux
python:
- 3.5
- 3.6
- 3.7
# blocklist branches
branches:
  except:
  - requires-io-master
install:
- pip install -r requirements-test.txt
- pip install .[tests] coveralls
script:
- py.test -v --cov tzf.pyramid_routing tests/
after_success:
- coveralls
jobs:
  include:
  - stage: linters
    python: 3.7
    install:
    - pip install -r requirements-lint.txt
    - pip install .[tests]
    script:
    - pycodestyle
    - pydocstyle
    - pylint tzf.pyramid_routing tests
    after_success: skip
  - stage: deploy
    python: 3.7
    if: tag IS present
    script: skip
    # deploy section
    deploy:
      provider: pypi
      user: fizyk
      password:
        secure: OSLxLtm6QWvQ8VqtDZJ4WHBcV+qltywELCBdZbjw+P4qxbokSXGJeDTGVBYQepdSLi1P6wv9R3FdAiYZppMaLhoBWZPs62VCDFZdHNPjXKrbNFCObo9qa3PQv23q6mkg8R3oHBB+nupL8ST3LWaQIJLP5QEiQ9jxuXPbSyhydQ8=
      on:
        tags: true
        repo: fizyk/pyramid_routing
      distributions: bdist_wheel
