language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - "python setup.py install"
    - "pip install tzf.pyramid_routing[tests] coveralls --use-mirrors"
script:
    - "py.test --cov tzf.pyramid_routing tests/"
after_success:
    - coveralls
