language: python
sudo: false
os:
  - linux
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - "pip install -r requirements-test.txt"
    - "python setup.py install"
    - "pip install tzf.pyramid_routing[tests] coveralls"
script:
    - "py.test -v --cov tzf.pyramid_routing tests/"
    - "pylama"
after_success:
    - coveralls

# deploy section
deploy:
    provider: pypi
    user: fizyk
    password:
        secure: OSLxLtm6QWvQ8VqtDZJ4WHBcV+qltywELCBdZbjw+P4qxbokSXGJeDTGVBYQepdSLi1P6wv9R3FdAiYZppMaLhoBWZPs62VCDFZdHNPjXKrbNFCObo9qa3PQv23q6mkg8R3oHBB+nupL8ST3LWaQIJLP5QEiQ9jxuXPbSyhydQ8=
    on:
        tags: true
        repo: fizyk/pyramid_routing
    distributions: "sdist bdist bdist_wheel"
